version: 2

sources:
  - name: raw
    database: deve_db
    schema: raw
    tables:
      - name: dmart_raw

      - name: customer_details
      - name: customer_details_no_update
      - name: order_details
      - name: order_details_di